steps:
  # 1. Build & Test the Spring Boot Application using Gradle
  - name: 'gradle:7.3.3-jdk17'
    entrypoint: 'gradle'
    args: ['clean', 'build', '--no-daemon']

  # 2. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/student-repo/student-details:$SHORT_SHA', '.']

  # 3. Push Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/student-repo/student-details:$SHORT_SHA']

  # 4. Deploy to Cloud Run in Mumbai (asia-south1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'student-details'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/student-repo/student-details:$SHORT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  # ✅ Use region-based log bucket

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/student-repo/student-details:$SHORT_SHA'
