steps:
  # 1. Set Working Directory & Clean Cache
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'mkdir -p /workspace/.gradle && rm -rf /workspace/.gradle/caches && echo "Gradle cache reset in /workspace"'

  # 2. Build & Test the Spring Boot Application
  - name: 'gradle:7.3.3-jdk17'
    entrypoint: 'gradle'
    args: ['clean', 'build', '--no-daemon', '--refresh-dependencies']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'  # ✅ Force Gradle to use /workspace

  # 3. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/student-repo/student-details:$SHORT_SHA', '.']

  # 4. Push Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/student-repo/student-details:$SHORT_SHA']

  # 5. Deploy to Cloud Run in Mumbai (asia-south1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'student-details'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/student-repo/student-details:$SHORT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: 'E2_HIGHCPU_8'  # ✅ Increase CPU for better performance

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/student-repo/student-details:$SHORT_SHA'
